name: Build and Deploy TWPUB Website

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false 
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Build Site
        run: npm run build
      - name: Deploy Content
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: output
